export const narutoText = [
  `Dattebyo, guts you'll never catch me! Oiroke no Justsu! Mukashi youko are keri sono kitsune kokonotsu no o ari sono o ichido buri raba yamakuzure tsunami tatsu kore ni kouji tehito domo nin no yakare wo atsume keri. Wazuka one nin ga shinobinomono seishi wo kake kore wo fuuin seshimeru sono mono shi ne keri sono shinobinomon na wo yon daime hokage to mousu. What is this decree? naruto no nakigoe. Kage Bunshin No Jutsu`,
  `Kiri no anstsusha! Stupid Sasuke. Kawarimi no Jutsu! Iku ze, koitsu wo taosu ni ha mou kno te shika nee. Sasuke! Here it is  Dattebyo! uwa uwa. Omae ha yo? that's not what I'm asking...nna koto kii ten jya nee no ore tte ba. datte yo ano sai fu kiri ga. nattoku dekire ka. So you noticed Kakashi Sensei? Ano sa ano kotsu oshie te kun nai?`,
  `Konbi Henge Whoa, I was about to get flattened... I'll end this lickety-split! Well, guess which one of us is real!  I'll give it a try, itsumo no chaura datte ba yo... Listen up We're going to have a battle royal now. Yoshi kore de iinda na. Boar, dog, bird, money, sheep ninpou Kuchiyose no Jutsu, tadpole boing. otamajyakushi... oi Gamatatsu why did you come out? ga-ganba reru kana.`,
  `Enough! te mexe iikagen ni shi yagare!! HAXA DAXA! kusso... as for me I stand by my words! That's my Way of the Ninja. Old Lady Tsunade. I will definitely win the unlucky necklace from you. Kage bunshin No Jutsu ... fuxtsu daijyoubu datte ba yo. ore ha Hokage ni naru made until I become the hokage. This way I got a hold of you. Lets go! Compress Chakra and todome kiru haxtsu Rasengan!`,
  `Sou kax neechan ga tasuke tekure ta n da...Arigato na! no seriously you saved me I'm Uzumaki Naruto. hehehehe. A mission of course. To exterminate the demaen of the Ocean that has been troubling this country. neechan. kora, omae ra.  kurae kakashe sense kara osowatta Leaf Village Secret Ultimate Taijustu technique konah kakura hiden taijyutsu ougi sen nen koroshi! A thousand years of death. sou Datte Ba Yo That's right. because he resembles me onaji you na sabishi sa toka kanashi sa tok kanji te iki te ki ta kara jibun no tame dake ni tatakai tsuzuke te ki ta aitsu wo tsuyoi to in solitude for himself. the spiraling series of Natuto Uzumaki's Ninja Handbook starts now! Do Rya NA! Ru! To! 2k Usuamaki naruto nisen rendan`,
  `Odama Rasengan oiroke no jutsu. now that its settled lets get to the land of rice paddies. touzoku ha orera ga nantoka sukkara. We'll deal with the bandits. Kon jyutsu ga are ba aitsu ni nante make nee tte ba yo. I won't lose to the likes of this guy. If I have this jutsu. We'll save you Menma`,
  `You Kega ha nee ka you. Are you hurt? bibiri kun scaredy cat. Datt te ba yo Sasuke! zettai ore no shitteru sasuke jya nee. dammit let me go ku soxtsu, kono yarou chikusho let me go! a failures true power is nakigoe aa wakaru tte ba yo I do understand. so what of it? nani ? fun kakko tsuken jya nee yo. it's not just you who is special even though she fought you with that in her mind. Omae Datte sou da. are you attempting to go against destiny? That's it the nine tailed fox chakra I'll use that!`,
  `for a friend. kikzutte demo tsure te kaeru! and take you back home even if i have to drag you.Kage Bunchin no Jutsu! Rasengan maru daxa ra whoosh spiral chidori chakra water explosion circle of energy. you are my closest friend sasuke actually said that to me that's why I have to chikusho, chikusho, splash water walk ano jutsu ku soxtsu. omae to ore ha chigaisugi ta kara kuyashii kara ore no raibaru ni katte ni kime ta. I didn't want to lose to you. the fact that we are friends. kyubi Chakra DA TTE BA YO!!!`,
];

export const sasuskeText = [``];
